### ISSUE TITLE
Update  County Presidential Results

### ISSUE THREAD

**Issue by Temexpert** [john-guerra/US_Elections_Results#4]
All States  have certified Presidential election results at the  county level  with the exception of Hawaii.   Can we  update  the results  here as well as there is a substantial variance from original extractions?

**Comment by john-guerra** [comment]
Sure, if you get the data in the same format I can update the viz. Pls send
a PR

John.
From my phone, brevity and all
http://johnguerra.co

**Comment by john-guerra** [comment]
Closing old one

**Comment by john-guerra** [comment]
Closing old one
